<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LaptopSeeder extends Seeder
{
	public function run(): void
	{
		$laptops = [
			[
				'id_admin' => 1,
				'id_laptop' => 2,
				'merek' => 'Apple',
				'model' => 'MacBook Pro',
				'harga' => 22774730,
				'processor' => 'Intel Core i5',
				'ghz' => 2.3,
				'ram' => 8,
				'storage' => 128,
				'gpu' => 'Intel Iris Plus Graphics 640',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 3,
				'merek' => 'Apple',
				'model' => 'Macbook Air',
				'harga' => 15281980,
				'processor' => 'Intel Core i5',
				'ghz' => 1.8,
				'ram' => 8,
				'storage' => 128,
				'gpu' => 'Intel HD Graphics 6000',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 4,
				'merek' => 'HP',
				'model' => '250 G6',
				'harga' => 9775000,
				'processor' => 'Intel Core i5 7200U',
				'ghz' => 2.5,
				'ram' => 8,
				'storage' => 256,
				'gpu' => 'Intel HD Graphics 620',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 5,
				'merek' => 'Apple',
				'model' => 'MacBook Pro',
				'harga' => 43136650,
				'processor' => 'Intel Core i7',
				'ghz' => 2.7,
				'ram' => 16,
				'storage' => 512,
				'gpu' => 'AMD Radeon Pro 455',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 6,
				'merek' => 'Apple',
				'model' => 'MacBook Pro',
				'harga' => 30661200,
				'processor' => 'Intel Core i5',
				'ghz' => 3.1,
				'ram' => 8,
				'storage' => 256,
				'gpu' => 'Intel Iris Plus Graphics 650',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 7,
				'merek' => 'Acer',
				'model' => 'Aspire 3',
				'harga' => 6800000,
				'processor' => 'AMD A9-Series 9420',
				'ghz' => 3.0,
				'ram' => 4,
				'storage' => 500,
				'gpu' => 'AMD Radeon R5',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 8,
				'merek' => 'Apple',
				'model' => 'MacBook Pro',
				'harga' => 36379490,
				'processor' => 'Intel Core i7',
				'ghz' => 2.2,
				'ram' => 16,
				'storage' => 256,
				'gpu' => 'Intel Iris Pro Graphics',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 9,
				'merek' => 'Apple',
				'model' => 'Macbook Air',
				'harga' => 19697900,
				'processor' => 'Intel Core i5',
				'ghz' => 1.8,
				'ram' => 8,
				'storage' => 256,
				'gpu' => 'Intel HD Graphics 6000',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 10,
				'merek' => 'Asus',
				'model' => 'ZenBook UX430UN',
				'harga' => 25415000,
				'processor' => 'Intel Core i7 8550U',
				'ghz' => 1.8,
				'ram' => 16,
				'storage' => 512,
				'gpu' => 'Nvidia GeForce MX150',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 11,
				'merek' => 'Acer',
				'model' => 'Swift 3',
				'harga' => 13090000,
				'processor' => 'Intel Core i5',
				'ghz' => 1.6,
				'ram' => 8,
				'storage' => 256,
				'gpu' => 'Intel UHD Graphics 620',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 12,
				'merek' => 'HP',
				'model' => '250 G6',
				'harga' => 6696300,
				'processor' => 'Intel Core i5 7200U',
				'ghz' => 2.5,
				'ram' => 4,
				'storage' => 500,
				'gpu' => 'Intel HD Graphics 620',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 13,
				'merek' => 'HP',
				'model' => '250 G6',
				'harga' => 5864830,
				'processor' => 'Intel Core i3 6006U',
				'ghz' => 2.0,
				'ram' => 4,
				'storage' => 500,
				'gpu' => 'Intel HD Graphics 520',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 14,
				'merek' => 'Apple',
				'model' => 'MacBook Pro',
				'harga' => 41479490,
				'processor' => 'Intel Core i7',
				'ghz' => 2.8,
				'ram' => 16,
				'storage' => 256,
				'gpu' => 'AMD Radeon Pro 555',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 15,
				'merek' => 'Dell',
				'model' => 'Inspiron 3567',
				'harga' => 8481300,
				'processor' => 'Intel Core i3 6006U',
				'ghz' => 2.0,
				'ram' => 4,
				'storage' => 256,
				'gpu' => 'AMD Radeon R5 M430',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 16,
				'merek' => 'Apple',
				'model' => 'MacBook 12"',
				'harga' => 21460800,
				'processor' => 'Intel Core M m3',
				'ghz' => 1.2,
				'ram' => 8,
				'storage' => 256,
				'gpu' => 'Intel HD Graphics 615',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 17,
				'merek' => 'Apple',
				'model' => 'MacBook Pro',
				'harga' => 25815350,
				'processor' => 'Intel Core i5',
				'ghz' => 2.3,
				'ram' => 8,
				'storage' => 256,
				'gpu' => 'Intel Iris Plus Graphics 640',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 18,
				'merek' => 'Dell',
				'model' => 'Inspiron 3567',
				'harga' => 12665000,
				'processor' => 'Intel Core i7',
				'ghz' => 2.7,
				'ram' => 8,
				'storage' => 256,
				'gpu' => 'AMD Radeon R5 M430',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 19,
				'merek' => 'Apple',
				'model' => 'MacBook Pro',
				'harga' => 48586000,
				'processor' => 'Intel Core i7',
				'ghz' => 2.9,
				'ram' => 16,
				'storage' => 512,
				'gpu' => 'AMD Radeon Pro 560',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 20,
				'merek' => 'Lenovo',
				'model' => 'IdeaPad 320-15IKB',
				'harga' => 8483000,
				'processor' => 'Intel Core i3 7100U',
				'ghz' => 2.4,
				'ram' => 8,
				'storage' => 1000,
				'gpu' => 'Nvidia GeForce 940MX',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 21,
				'merek' => 'Dell',
				'model' => 'XPS 13',
				'harga' => 16643000,
				'processor' => 'Intel Core i5',
				'ghz' => 1.6,
				'ram' => 8,
				'storage' => 128,
				'gpu' => 'Intel UHD Graphics 620',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 22,
				'merek' => 'Asus',
				'model' => 'Vivobook E200HA',
				'harga' => 3262300,
				'processor' => 'Intel Atom x5-Z8350',
				'ghz' => 1.44,
				'ram' => 2,
				'storage' => 32,
				'gpu' => 'Intel HD Graphics 400',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 23,
				'merek' => 'Lenovo',
				'model' => 'Legion Y520-15IKBN',
				'harga' => 16983000,
				'processor' => 'Intel Core i5',
				'ghz' => 2.5,
				'ram' => 8,
				'storage' => 1128,
				'gpu' => 'Nvidia GeForce GTX 1050',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 24,
				'merek' => 'HP',
				'model' => '255 G6',
				'harga' => 4386000,
				'processor' => 'AMD E-Series E2-9000e',
				'ghz' => 1.5,
				'ram' => 4,
				'storage' => 500,
				'gpu' => 'AMD Radeon R2',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 25,
				'merek' => 'Dell',
				'model' => 'Inspiron 5379',
				'harga' => 13923000,
				'processor' => 'Intel Core i5',
				'ghz' => 1.6,
				'ram' => 8,
				'storage' => 256,
				'gpu' => 'Intel UHD Graphics 620',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 26,
				'merek' => 'HP',
				'model' => '15-BS101nv',
				'harga' => 11203000,
				'processor' => 'Intel Core i7',
				'ghz' => 1.8,
				'ram' => 8,
				'storage' => 256,
				'gpu' => 'Intel HD Graphics 620',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 27,
				'merek' => 'Dell',
				'model' => 'Inspiron 3567',
				'harga' => 7116880,
				'processor' => 'Intel Core i3 6006U',
				'ghz' => 2.0,
				'ram' => 4,
				'storage' => 1000,
				'gpu' => 'Intel HD Graphics 520',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 28,
				'merek' => 'Apple',
				'model' => 'MacBook Air',
				'harga' => 18683000,
				'processor' => 'Intel Core i5',
				'ghz' => 1.6,
				'ram' => 8,
				'storage' => 128,
				'gpu' => 'Intel HD Graphics 6000',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 29,
				'merek' => 'Dell',
				'model' => 'Inspiron 5570',
				'harga' => 13600000,
				'processor' => 'Intel Core i5',
				'ghz' => 1.6,
				'ram' => 8,
				'storage' => 256,
				'gpu' => 'AMD Radeon 530',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 30,
				'merek' => 'Dell',
				'model' => 'Latitude 5590',
				'harga' => 22066000,
				'processor' => 'Intel Core i7',
				'ghz' => 1.9,
				'ram' => 8,
				'storage' => 512,
				'gpu' => 'Intel UHD Graphics 620',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 31,
				'merek' => 'HP',
				'model' => 'ProBook 470',
				'harga' => 15232000,
				'processor' => 'Intel Core i5',
				'ghz' => 1.6,
				'ram' => 8,
				'storage' => 1000,
				'gpu' => 'Nvidia GeForce 930MX',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 32,
				'merek' => 'Chuwi',
				'model' => 'LapBook 15.6"',
				'harga' => 4164830,
				'processor' => 'Intel Atom x5-Z8300',
				'ghz' => 1.44,
				'ram' => 4,
				'storage' => 64,
				'gpu' => 'Intel HD Graphics',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 33,
				'merek' => 'Asus',
				'model' => 'E402WA-GA010T',
				'harga' => 3383000,
				'processor' => 'AMD E-Series E2-6110',
				'ghz' => 1.5,
				'ram' => 2,
				'storage' => 32,
				'gpu' => 'AMD Radeon R2',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 34,
				'merek' => 'HP',
				'model' => '17-ak001nv',
				'harga' => 7463000,
				'processor' => 'AMD A6-Series 9220',
				'ghz' => 2.5,
				'ram' => 4,
				'storage' => 500,
				'gpu' => 'AMD Radeon 530',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 35,
				'merek' => 'Dell',
				'model' => 'XPS 13',
				'harga' => 31773000,
				'processor' => 'Intel Core i7',
				'ghz' => 1.8,
				'ram' => 16,
				'storage' => 512,
				'gpu' => 'Intel UHD Graphics 620',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 36,
				'merek' => 'Apple',
				'model' => 'MacBook Air',
				'harga' => 16966000,
				'processor' => 'Intel Core i5',
				'ghz' => 1.6,
				'ram' => 8,
				'storage' => 256,
				'gpu' => 'Intel HD Graphics 6000',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 37,
				'merek' => 'Lenovo',
				'model' => 'IdeaPad 120S-14IAP',
				'harga' => 4233000,
				'processor' => 'Intel Celeron Dual Core N3350',
				'ghz' => 1.1,
				'ram' => 4,
				'storage' => 64,
				'gpu' => 'Intel HD Graphics 500',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 38,
				'merek' => 'Acer',
				'model' => 'Aspire 3',
				'harga' => 6239000,
				'processor' => 'Intel Core i3',
				'ghz' => 2.7,
				'ram' => 4,
				'storage' => 1000,
				'gpu' => 'Intel HD Graphics 620',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 39,
				'merek' => 'Dell',
				'model' => 'Inspiron 5770',
				'harga' => 16643000,
				'processor' => 'Intel Core i5',
				'ghz' => 1.6,
				'ram' => 8,
				'storage' => 1128,
				'gpu' => 'AMD Radeon 530',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 40,
				'merek' => 'HP',
				'model' => '250 G6',
				'harga' => 8307730,
				'processor' => 'Intel Core i5 7200U',
				'ghz' => 2.5,
				'ram' => 4,
				'storage' => 1000,
				'gpu' => 'Intel HD Graphics 620',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 41,
				'merek' => 'HP',
				'model' => 'ProBook 450',
				'harga' => 14943000,
				'processor' => 'Intel Core i5',
				'ghz' => 1.6,
				'ram' => 8,
				'storage' => 256,
				'gpu' => 'Nvidia GeForce 930MX',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 42,
				'merek' => 'Toshiba',
				'model' => 'Satellite Pro',
				'harga' => 13481000,
				'processor' => 'Intel Core i5 7200U',
				'ghz' => 2.5,
				'ram' => 8,
				'storage' => 128,
				'gpu' => 'Intel HD Graphics 620',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 43,
				'merek' => 'Xiaomi',
				'model' => 'Mi Notebook',
				'harga' => 20383000,
				'processor' => 'Intel Core i5',
				'ghz' => 1.6,
				'ram' => 8,
				'storage' => 256,
				'gpu' => 'Nvidia GeForce MX150',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 44,
				'merek' => 'Dell',
				'model' => 'Inspiron 7773',
				'harga' => 26333000,
				'processor' => 'Intel Core i7',
				'ghz' => 1.8,
				'ram' => 16,
				'storage' => 512,
				'gpu' => 'Nvidia GeForce 150MX',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 45,
				'merek' => 'Dell',
				'model' => 'XPS 15',
				'harga' => 40749000,
				'processor' => 'Intel Core i7',
				'ghz' => 2.8,
				'ram' => 16,
				'storage' => 512,
				'gpu' => 'Nvidia GeForce GTX 1050',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 46,
				'merek' => 'Lenovo',
				'model' => 'Legion Y520-15IKBN',
				'harga' => 13243000,
				'processor' => 'Intel Core i5',
				'ghz' => 2.5,
				'ram' => 8,
				'storage' => 256,
				'gpu' => 'Nvidia GeForce GTX 1050',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 47,
				'merek' => 'Acer',
				'model' => 'Swift 7',
				'harga' => 16813000,
				'processor' => 'Intel Core i5',
				'ghz' => 1.2,
				'ram' => 8,
				'storage' => 256,
				'gpu' => 'Intel HD Graphics 615',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 48,
				'merek' => 'Dell',
				'model' => 'Inspiron 5770',
				'harga' => 18445000,
				'processor' => 'Intel Core i7',
				'ghz' => 1.8,
				'ram' => 8,
				'storage' => 1128,
				'gpu' => 'AMD Radeon 530',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 49,
				'merek' => 'Lenovo',
				'model' => 'Thinkpad Yoga',
				'harga' => 48008000,
				'processor' => 'Intel Core i7',
				'ghz' => 2.7,
				'ram' => 16,
				'storage' => 1000,
				'gpu' => 'Intel HD Graphics 620',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 50,
				'merek' => 'Vero',
				'model' => 'K147',
				'harga' => 4420000,
				'processor' => 'Intel Celeron Dual Core N3350',
				'ghz' => 1.1,
				'ram' => 4,
				'storage' => 32,
				'gpu' => 'Intel HD Graphics 500',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 51,
				'merek' => 'Xiaomi',
				'model' => 'Mi Notebook',
				'harga' => 16998300,
				'processor' => 'Intel Core i5 7200U',
				'ghz' => 2.5,
				'ram' => 8,
				'storage' => 256,
				'gpu' => 'Nvidia GeForce MX150',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 52,
				'merek' => 'Lenovo',
				'model' => 'IdeaPad 320-17IKBR',
				'harga' => 11866000,
				'processor' => 'Intel Core i5',
				'ghz' => 1.6,
				'ram' => 8,
				'storage' => 256,
				'gpu' => 'Nvidia GeForce MX150',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 53,
				'merek' => 'Dell',
				'model' => 'Inspiron 5379',
				'harga' => 14263000,
				'processor' => 'Intel Core i7',
				'ghz' => 1.8,
				'ram' => 8,
				'storage' => 1000,
				'gpu' => 'Intel UHD Graphics 620',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 54,
				'merek' => 'HP',
				'model' => 'ProBook 470',
				'harga' => 15538000,
				'processor' => 'Intel Core i5',
				'ghz' => 1.6,
				'ram' => 8,
				'storage' => 1000,
				'gpu' => 'Nvidia GeForce 930MX',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 55,
				'merek' => 'Razer',
				'model' => 'Blade Pro',
				'harga' => 103683000,
				'processor' => 'Intel Core i7',
				'ghz' => 2.9,
				'ram' => 32,
				'storage' => 1000,
				'gpu' => 'Nvidia GeForce GTX 1080',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 56,
				'merek' => 'HP',
				'model' => 'ProBook 430',
				'harga' => 16303000,
				'processor' => 'Intel Core i5',
				'ghz' => 1.6,
				'ram' => 8,
				'storage' => 512,
				'gpu' => 'Intel UHD Graphics 620',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 57,
				'merek' => 'HP',
				'model' => 'Omen 17-W295',
				'harga' => 23443000,
				'processor' => 'Intel Core i7',
				'ghz' => 2.8,
				'ram' => 16,
				'storage' => 1256,
				'gpu' => 'Nvidia GeForce GTX 1050',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 58,
				'merek' => 'HP',
				'model' => 'Probook 470',
				'harga' => 17765000,
				'processor' => 'Intel Core i7',
				'ghz' => 1.8,
				'ram' => 8,
				'storage' => 256,
				'gpu' => 'Nvidia GeForce 930MX',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 59,
				'merek' => 'Dell',
				'model' => 'Inspiron 7577',
				'harga' => 31365000,
				'processor' => 'Intel Core i7',
				'ghz' => 2.8,
				'ram' => 16,
				'storage' => 1512,
				'gpu' => 'Nvidia GeForce GTX 1060',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 60,
				'merek' => 'Lenovo',
				'model' => 'V110-15ISK',
				'harga' => 8381000,
				'processor' => 'Intel Core i5',
				'ghz' => 2.3,
				'ram' => 4,
				'storage' => 128,
				'gpu' => 'Intel HD Graphics 520',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 61,
				'merek' => 'Acer',
				'model' => 'Aspire E5-576G',
				'harga' => 12614000,
				'processor' => 'Intel Core i7',
				'ghz' => 2.7,
				'ram' => 8,
				'storage' => 1000,
				'gpu' => 'Nvidia GeForce 940MX',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 62,
				'merek' => 'Lenovo',
				'model' => 'Legion Y720-15IKB',
				'harga' => 29733000,
				'processor' => 'Intel Core i7',
				'ghz' => 2.8,
				'ram' => 16,
				'storage' => 1512,
				'gpu' => 'Nvidia GeForce GTX 1060',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'id_admin' => 1,
				'id_laptop' => 63,
				'merek' => 'Dell',
				'model' => 'Precision 7520',
				'harga' => 51935000,
				'processor' => 'Intel Xeon E3-1505M V6',
				'ghz' => 3.0,
				'ram' => 16,
				'storage' => 1256,
				'gpu' => 'Nvidia Quadro M1200',
				'ukuran_baterai' => null,
				'gambar' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
		];

		DB::table('master_laptop')->insert($laptops);
	}

	private function escapeString($string)
	{
		return str_replace("'", "\'", $string);
	}
}
